name: 'Set up Qob'
description: 'Install a specific Qob version for use in your workflow.'
author: 'Shen, Jen-Chieh'
inputs:
  version:
    description: 'The version of Qob to install, e.g. "0.0.8", or "snapshot" for a recent development version.'
    default: 'snapshot'
  architecture:
    description: 'The target architecture (x64, arm64) of the Qob-CLI.'
    default: 'x64'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
